### ISSUE TITLE
Megatris: Should not allow infinite rotation per tetramino

### ISSUE THREAD

**Issue by felipesanches** [Uzebox/uzebox#61] opened 2016-08-07 18:38 UTC
During gameplay, if the player keeps quickly rotating the tetramino, then the game will never give you a new tetramino. This can be used as a way of cheating in the game.

I suggest that there should be a timeout for each tetramino that starts counting once the tetramino touches other blocks in the playfield.

**Comment by uze6666** [comment] 2016-08-16 17:42
Hi Felipe, this is a feature, not a bug. The reference was TetrisDS gameplay which allows it. That said, there could be an option in the oprtions menu to turn it off.

**Comment by weber21w** [comment] 2017-07-03 03:53
Theoretically in a versus match, it would be a terrible tactic as they build up much garbage against you while you screw around with 1 piece. Now if one was clearly going to lose, they might rotate indefinitely to not allow the opponents garbage to come and cause a loss. It seems to me this is one of those things that is easily fixed with a punch to the guy sitting next to you, otherwise are there ideas on the easiest way to implement this in code avoiding the justified physical punch? If so lets implement it.

**Closed** 2023-07-07 07:17 UTC
